/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.sql.ResultSet;
import java.sql.*;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author student
 */
public class RecipientForm extends javax.swing.JFrame {

    private ResultSet rs;
    private boolean insertStr;

    /**
     * Creates new form SubscribeForm
     * @throws java.lang.Exception
     */
    public RecipientForm () throws  Exception{
        
         mdbc=new MyDBConnection();
         mdbc.init();
         Connection conn=mdbc.getMyConnection();
         stmt= conn.createStatement();
        
        initComponents();
    }
     public ResultSet getResultFromRec() {
        
        ResultSet rs=null;
        
        try{
            rs=stmt.executeQuery("Select * from Recipient");
        
        }
        catch(SQLException e){}
        
        return rs;
        
    }
 public String quotate(String content){
    
        return "'"+content+"'";
    }     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        SendPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Получатель");
        setLocation(new java.awt.Point(700, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        DataPanel.setLayout(new java.awt.GridLayout(5, 2, 1, 2));

        jLabel1.setText("id пользователя:");
        DataPanel.add(jLabel1);
        DataPanel.add(jTextField1);

        jLabel2.setText("ФИО:");
        DataPanel.add(jLabel2);
        DataPanel.add(jTextField2);

        jLabel3.setText("Улица проживания:");
        DataPanel.add(jLabel3);
        DataPanel.add(jTextField3);

        jLabel4.setText("№ дома:");
        DataPanel.add(jLabel4);

        jTextField4.setToolTipText("");
        DataPanel.add(jTextField4);

        jLabel5.setText("№ квартиры:");
        DataPanel.add(jLabel5);
        DataPanel.add(jTextField5);

        SendPanel.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        SendPanel.add(jButton1);

        jButton2.setText("Редактировать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        SendPanel.add(jButton2);

        jButton3.setText("Удалить");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        SendPanel.add(jButton3);

        jButton4.setText("Найти");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        SendPanel.add(jButton4);

        ResultSet rs = getResultFromRec();
        jTable1.setModel(new Admin.Recipient(rs));
        mdbc.close(rs);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SendPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(SendPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 653, 492);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String id_rec=jTextField1.getText();
        String FIO=jTextField2.getText();        
        String Street=jTextField3.getText();
        String N_house=jTextField4.getText();
        String N_flat=jTextField5.getText();
        
        String insertStr="";
        
        try{
            
            insertStr="insert into Recipient (id_recipient, FIO, Street, N_house, N_flat) values('"
                    +id_rec+"','"
                    +FIO+"','"
                    +Street+"','"
                    +N_house+"','"
                    +N_flat
                    +"')";
            
            int done=stmt.executeUpdate(insertStr);
            
           
           
            getContentPane().removeAll();
            initComponents();
        
        }
        catch(SQLException e){
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id_rec=jTextField1.getText();
        String FIO=jTextField2.getText();        
        String Street=jTextField3.getText();
        String N_house=jTextField4.getText();
        String N_flat=jTextField5.getText();
        
        String EditStr="";
         
        try{
            
            EditStr="UPDATE Recipient set FIO=" + quotate(FIO) + "," + "Street=" + quotate(Street) + "," + "N_house=" + quotate(N_house) + "," + "N_flat=" + quotate(N_flat) + "where id_recipient=" + quotate(id_rec);
            
            int done=stmt.executeUpdate(EditStr);
            getContentPane().removeAll();
            initComponents();
        
        }
        catch(SQLException e){
            System.out.println(insertStr);
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id_rec=jTextField1.getText();
        
        String DeleteStr="";
          try{
            
            DeleteStr="DELETE FROM Recipient WHERE Id_recipient=" + quotate(id_rec);
                    
            int done=stmt.executeUpdate(DeleteStr);
            getContentPane().removeAll();
            initComponents();
        
        }
        catch(SQLException e){
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(Authorization.Test==2) {
            this.jButton1.setVisible(false);
            this.jButton2.setVisible(false);
            this.jButton3.setVisible(false);
        };
    }//GEN-LAST:event_formWindowActivated

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String Find=jTextField1.getText();
        Recipient table = (Recipient)jTable1.getModel();
        TableRowSorter <Recipient> tr = new TableRowSorter <Recipient>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(Find,0));
        jTextField1.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try{
                new RecipientForm().setVisible(true);
            }
            catch(Exception e){
            }
        });
            }


  
private final MyDBConnection mdbc;
private final java.sql.Statement stmt;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataPanel;
    private javax.swing.JPanel SendPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables


}
